env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
ignorePatterns: ["jquery.serializejson.js"]
rules: {
  semi: [2, "always"]
}