image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - npm install --save-dev eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
  - npm install --save-dev stylelint stylelint-scss stylelint-config-recommended-scss
  - npm i
stages:
  - lint
  - test
  - deploy

eslint:
  stage: lint
  script:
  - npx eslint .
  tags:
  - docker

stylelint:
  stage: lint
  script:
  - npx stylelint ./sass --config .stylelintrc.yml
  tags:
  - docker

unit-tests:
  stage: test
  script: 
  - ./node_modules/mocha/bin/mocha --recursive \"test/\"
  tags:
  - docker
  
production:
  stage: deploy
  image: ruby:latest
  script:
  - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
  - master