image: node:latest

before_script:
  - npm install --save-dev eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
  - npm i
stages:
  - lint
#  - test

eslint:
  stage: lint
  script:
  - npx eslint .
  tags:
  - docker

#unit-tests:
#  stage: test
#  script:
#  - ./node_modules/mocha/bin/mocha --recursive \"test/\"
#  tags:
#  - docker
